name: GitHub Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.10.4
       
      - name: Install cloudmesh-cc
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .
          cms help
          make doc
          mkdir -p /home/runner/.cloudmesh/workflow
      - name: Environment
        run: |
          echo $USER
          echo $HOME
      - name: Build Sphinx Site
        run: |
          make html -C docs
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html
          #destination_dir: latest 
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
