# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python -m pip install -r requirements.txt
        python -m pip install -e .
        cms help
        mkdir -p /home/runner/.cloudmesh/workflow
        echo $USER
        echo $HOME
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 cloudmesh --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 cloudmesh --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # Enable CMS Debug for testing
        # If you remove, the nlp test cases for commands without --nocm will fail.
        cms debug on
        python -m pip install -e .
        # tests need api key so we cannot automate them
        # coverage run -m pytest tests/test_001_cc.py tests/test_002_cc_labelmaker.py
    - name: Create wheel
      run: |
        python setup.py sdist bdist_wheel
